// ============================================================================
// STUDY BUILD NOTE:
// This file intentionally contains NO `using` directives. Every type is written
// with its FULL namespace path (e.g. Microsoft.UI.Xaml.Controls.TabView) so you
// can see exactly which library/namespace each class comes from.
// In real production code you would normally add `using` lines at the top
// (e.g. `using Microsoft.UI.Xaml.Controls;`) to keep names short.
// ============================================================================

// `namespace` is NOT a `using`. It DECLARES where our class lives, giving the
// class the full name `sutty.UI.Views.MainWindow`. Other code references it by
// that path (or by adding `using sutty.UI.Views;`).
namespace sutty.UI.Views
{
    /// <summary>
    /// The application's main window — the top-level OS window the user sees.
    /// </summary>
    // Modifiers explained:
    //   public  -> other assemblies/projects can see this class.
    //   sealed  -> no class is allowed to inherit from MainWindow.
    //   partial -> this class is split across multiple files. The XAML compiler
    //              auto-generates the other half (MainWindow.g.cs) which holds
    //              InitializeComponent() and the strongly-typed fields for every
    //              x:Name in the XAML (CustomDragRegion, LeftNav, TitleTabs,
    //              ContentText). That is why we can use those names below without
    //              declaring them here.
    //   : Microsoft.UI.Xaml.Window -> MainWindow inherits from WinUI's Window
    //              base class, gaining members like ExtendsContentIntoTitleBar
    //              and SetTitleBar().
    public sealed partial class MainWindow : Microsoft.UI.Xaml.Window
    {
        // A read-only auto-property that holds this window's view model (its
        // data + logic layer that the UI binds to).
        //   { get; } means it can be assigned ONLY inside the constructor and is
        //   read-only everywhere else.
        public sutty.UI.ViewModels.MainViewModel ViewModel { get; }

        // The constructor: runs exactly once, when `new MainWindow()` executes.
        public MainWindow()
        {
            // Create the view model and store it in the property above.
            ViewModel = new sutty.UI.ViewModels.MainViewModel();

            // Generated by the XAML compiler. It parses MainWindow.xaml, builds
            // the visual tree, hooks up every event handler, and fills in the
            // x:Name fields. It MUST run before we touch any named control.
            InitializeComponent();

            // ---- Title bar customization ------------------------------------
            // Draw our own content up into the system title-bar area (removes the
            // default caption strip) so the tab strip can share the title line.
            ExtendsContentIntoTitleBar = true;

            // Tell WinUI which element behaves as the draggable title bar. We pass
            // the transparent Grid named "CustomDragRegion" in the XAML, which
            // fills the empty space to the right of the tabs.
            SetTitleBar(CustomDragRegion);

            // ---- Window icon (title bar + taskbar + Alt+Tab) ----------------
            // Step 1: Get the raw Win32 window handle (HWND) for this WinUI
            //         window. WindowNative.GetWindowHandle is a WinRT interop
            //         helper. System.IntPtr is the platform-sized pointer type
            //         used to represent an HWND in managed code.
            System.IntPtr hwnd = WinRT.Interop.WindowNative.GetWindowHandle(this);

            // Step 2: Convert that HWND into a WinUI WindowId. The Windows App
            //         SDK identifies windows by its own WindowId struct, not by
            //         the raw HWND.
            Microsoft.UI.WindowId windowId =
                Microsoft.UI.Win32Interop.GetWindowIdFromWindow(hwnd);

            // Step 3: Look up the high-level AppWindow object for that WindowId.
            //         AppWindow exposes window-management APIs such as SetIcon().
            Microsoft.UI.Windowing.AppWindow appWindow =
                Microsoft.UI.Windowing.AppWindow.GetFromWindowId(windowId);

            // Step 4: Build an absolute path to the .ico file shipped beside the
            //         running .exe.
            //           System.AppContext.BaseDirectory = folder the app started
            //             from (the output/bin folder at runtime).
            //           System.IO.Path.Combine = joins path segments using the
            //             correct separator, producing "...\Assets\sutty.ico".
            string iconPath = System.IO.Path.Combine(
                System.AppContext.BaseDirectory, "Assets", "sutty.ico");

            // Step 5: Apply the icon. This ONE call sets the icon shown in the
            //         title bar, the Windows taskbar, and the Alt+Tab switcher,
            //         because all three read from the window's icon.
            appWindow.SetIcon(iconPath);

            // ---- Initial navigation state -----------------------------------
            // Pre-select the first rail item so the app opens on a real page
            // instead of an empty selection. MenuItems[0] is the "Home" item.
            LeftNav.SelectedItem = LeftNav.MenuItems[0];
        }

        // Event handler: fires whenever the selected item in the LEFT RAIL
        // changes (user clicks a different nav icon).
        //   sender = the NavigationView that raised the event.
        //   args   = event data, including args.SelectedItem (the new selection).
        private void LeftNav_SelectionChanged(
            Microsoft.UI.Xaml.Controls.NavigationView sender,
            Microsoft.UI.Xaml.Controls.NavigationViewSelectionChangedEventArgs args)
        {
            // Pattern test + cast in one step: only enter the block if
            // SelectedItem really is a NavigationViewItem, binding it to `item`.
            if (args.SelectedItem is Microsoft.UI.Xaml.Controls.NavigationViewItem item)
            {
                // Show the item's Tag text in the center area.
                //   ?.  (null-conditional)  -> if the left side is null, skip the
                //        call and yield null instead of throwing.
                //   ??  (null-coalescing)   -> if the left side is null, use the
                //        right side instead. So: Tag if present, else Content.
                ContentText.Text = item.Tag?.ToString() ?? item.Content?.ToString();
            }
        }

        // Event handler: fires when a different TAB on the title line is selected.
        // TabView's SelectionChanged uses the classic Selector signature:
        //   (object sender, SelectionChangedEventArgs e)  -- note: plain `object`.
        private void TitleTabs_SelectionChanged(
            object sender,
            Microsoft.UI.Xaml.Controls.SelectionChangedEventArgs e)
        {
            // Verify the currently selected tab is a TabViewItem, cast into `tab`.
            if (TitleTabs.SelectedItem is Microsoft.UI.Xaml.Controls.TabViewItem tab)
            {
                // Mirror the selected tab's header text into the center content.
                ContentText.Text = tab.Header?.ToString();
            }
        }

        // Event handler: fires when the user clicks a tab's close (X) button.
        //   sender   = the TabView the tab belongs to.
        //   args.Tab = the specific TabViewItem the user asked to close.
        private void TitleTabs_TabCloseRequested(
            Microsoft.UI.Xaml.Controls.TabView sender,
            Microsoft.UI.Xaml.Controls.TabViewTabCloseRequestedEventArgs args)
        {
            // Remove that tab from the TabView's item collection, which makes it
            // disappear from the strip.
            sender.TabItems.Remove(args.Tab);
        }
    }
}
